---
abstract: 'obtain expiration date of certificate'
author:
  - 'HIROSE Masaaki  C<< <hirose31@gmail.com> >>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-SSL-ExpireDate
no_index:
  directory:
    - inc
    - t
requires:
  Class::Accessor: 0
  Crypt::OpenSSL::X509: 0
  Date::Parse: 0
  DateTime: 0
  DateTime::Duration: 0
  Filter::Util::Call: 0
  IO::Socket: 0
  Time::Duration::Parse: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.06
